elixir/rs_umbrella/apps/rs_web/lib/rs_web/router.ex
defmodule RsWeb.Router do
  use RsWeb, :router
  require Logger

  if Mix.env == :dev do
   forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RsWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug RsWeb.API.V1.Auth
    #plug RsWeb.Plug.ConnInterceptor
    # plug :token_authentication
    # plug :dispatch
  end

  pipeline :graphql do
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json, Absinthe.PlugParser],
    pass: ["*/*"],
    json_decoder: Jason
  end
  #
  #pipeline :graphql do
   # plug Absinthe.Plug,
    #  schema: RsWeb.Schema,
#

  #json_codec: Jason
  #end
  scope "/", RsWeb do
    pipe_through [:browser, :authenticate_user]
    get "/", PageController, :index
  end
  scope "/", RsWeb do
    pipe_through [:browser]

    #get "/league/register/:id", LeagueRegController, :register
    #get "/league/:messenger", LeagueRegController, :show
    get "/team", TeamRegController, :index

    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]

    get "/visit/:id", VisitController, :show

    #:id is for looking up the league
  end

  scope "/league", RsWeb do
    pipe_through [:browser,:authenticate_user]

    get "/register", LeagueRegController, :new
    get "/register/:id", LeagueRegController, :register

  end

  scope "/manage", RsWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/leagues", LeagueController
    resources "/teams", TeamController
  end

  scope "/links", RsWeb do
    get "/:id", LinkController, :get_and_redirect
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", RsWeb.API.V1 do
    pipe_through :api # :authenticate_user_from_token]
    # post "/leagues", LeagueController, :create
    resources "/leagues", LeagueController, only: [:index, :show, :create]
  end


  scope path: "/graphql" do
    # TODO using this context in assigns conn.private[:absinthe][:context] [:authenticate_user_from_token]
    pipe_through :graphql

    forward "/graphiql", Absinthe.Plug.GraphiQL,
        schema: RsWeb.Schema, json_codec: Jason
    forward "/graphql",
        Absinthe.Plug,
        schema: RsWeb.Schema, json_codec: Jason
   end

  scope "/test/api", RsWeb do
    pipe_through :api
    resources "/leagues", LeagueRegController

  end
end

elixir/rs_umbrella/apps/rs_web/lib/rs_web/controllers/user_controller.ex
defmodule RsWeb.UserController do
  use RsWeb, :controller

  alias Rs.Accounts
  alias Rs.Accounts.User
  alias RsWeb.Email
  alias RsWeb.Mailer
  require Logger

  plug :authenticate_user when action in [:index, :show]

  def new(conn, _params) do
    changeset = Accounts.change_registration(%User{}, %{})
    render(conn, "new.html", changeset: changeset, registered_user: false)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->

        Email.registration_email(user) |> Mailer.deliver_later()
        Logger.info("creating user with this connection:  #{inspect(conn)}")
        conn
        |> RsWeb.Auth.login(user)
        |> put_flash(:info, "#{user.name} created!")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user(id)
    render(conn, "show.html", user: user)
  end

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.html", users: users)
  end
end

elixir/rs_umbrella/apps/rs_web/lib/rs_web/views/user_view.ex
defmodule RsWeb.UserView do
  use RsWeb, :view

  alias Rs.Accounts

  def first_name(%Accounts.User{name: name}) do
    name
    |> String.split(" ")
    |> Enum.at(0)
  end

  def render("user.json", %{user: user}) do
    %{id: user.id, username: user.username}
  end
end

elixir/rs_umbrella/apps/rs_web/lib/rs_web/templates/user/index.html.eex
<h1> Listing Users</h1>

<table>
    <%= for user <- @users do %>
        <tr>
            <td>><%= render "user.html", user: user %> <%= link "View", to: Routes.user_path(@conn, :show, user.id) %>  </td>
        </tr>
    <% end %>
</table>  

elixir/rs_umbrella/apps/rs_web/lib/rs_web/templates/user/new.html.eex
<div class="container mx-auto flex flex-col h-full justify-center items-center">
<%= if @changeset.action do %>
            <div class="bg-orange-100 border-l-4 border-orange-500 text-orange-700 p-4" role="alert">
                <div class="text-red-500 text-xs italic">
                    <p>Oops, something went wrong!</p>
                </div>
            </div>
        <% end %>
<%= form_for @changeset, Routes.user_path(@conn, :create), [class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"], fn f -> %>

    <p class="mb-3 text-center font-sans text-3xl text-gray-800">Roy Hobbs Account</p>
    <%= label(:user, :nome, "Name", class: "block text-gray-700 text-sm font-bold mb-2") %>
    <%= text_input f, :name, placeholder: "Name", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    <%= error_tag f, :name %>
    <%= label(:user, :username, "Username", class: "block text-gray-700 text-sm font-bold mb-2") %>
    <%= text_input f, :username, placeholder: "Username", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    <%= error_tag f, :username %>
    <%= inputs_for f, :credential, fn cf -> %>
    <%= label(:credential, :email, class: "block text-gray-700 text-sm font-bold mb-2") %>
    <%= text_input cf, :email, placeholder: "Email", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        <%= error_tag cf, :email %>
    <%= label(:credential, :password, class: "block text-gray-700 text-sm font-bold mb-2") %>
    <%= password_input cf, :password, placeholder: "Password", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" %>
        <%= error_tag cf, :password %>       
    <% end %>
    <div class="flex items-center justify-between">
        <%= submit "Create Account", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
         <a class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" href="/sessions/new">
                    Cancel
         </a>
     </div>
<% end %>
</div>

elixir/rs_umbrella/apps/rs_web/lib/rs_web/templates/user/show.html.eex
<h1>User</h1>
<b><%= first_name(@user) %></b> (<%= @user.id %>)

elixir/rs_umbrella/apps/rs_web/lib/rs_web/templates/user/user.html.eex
<strong><%= first_name(@user) %> </strong> (<%= @user.id %>)