elixir/rs_umbrella/apps/rs_web/lib/rs_web/router.ex
defmodule RsWeb.Router do
  use RsWeb, :router
  require Logger

  if Mix.env == :dev do
   forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RsWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug RsWeb.API.V1.Auth
    #plug RsWeb.Plug.ConnInterceptor
    # plug :token_authentication
    # plug :dispatch
  end

  pipeline :graphql do
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json, Absinthe.PlugParser],
    pass: ["*/*"],
    json_decoder: Jason
  end
  #
  #pipeline :graphql do
   # plug Absinthe.Plug,
    #  schema: RsWeb.Schema,
#

  #json_codec: Jason
  #end
  scope "/", RsWeb do
    pipe_through [:browser, :authenticate_user]
    get "/", PageController, :index
  end
  scope "/", RsWeb do
    pipe_through [:browser]

    #get "/league/register/:id", LeagueRegController, :register
    #get "/league/:messenger", LeagueRegController, :show
    get "/team", TeamRegController, :index

    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]

    get "/visit/:id", VisitController, :show

    #:id is for looking up the league
  end

  scope "/league", RsWeb do
    pipe_through [:browser,:authenticate_user]

    get "/register", LeagueRegController, :new
    get "/register/:id", LeagueRegController, :register

  end

  scope "/manage", RsWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/leagues", LeagueController
    resources "/teams", TeamController
  end

  scope "/links", RsWeb do
    get "/:id", LinkController, :get_and_redirect
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", RsWeb.API.V1 do
    pipe_through :api # :authenticate_user_from_token]
    # post "/leagues", LeagueController, :create
    resources "/leagues", LeagueController, only: [:index, :show, :create]
  end


  scope path: "/graphql" do
    # TODO using this context in assigns conn.private[:absinthe][:context] [:authenticate_user_from_token]
    pipe_through :graphql

    forward "/graphiql", Absinthe.Plug.GraphiQL,
        schema: RsWeb.Schema, json_codec: Jason
    forward "/graphql",
        Absinthe.Plug,
        schema: RsWeb.Schema, json_codec: Jason
   end

  scope "/test/api", RsWeb do
    pipe_through :api
    resources "/leagues", LeagueRegController

  end
end

elixir/rs_umbrella/apps/rs_web/lib/rs_web/controllers/API/V1/league_controller.ex
defmodule RsWeb.API.V1.LeagueController do
  use RsWeb, :controller
  require Logger


  alias Rs.Organization

  def index(conn, _params) do
    leagues = Organization.list_leagues()
    render(conn, "index.json", leagues: leagues)
  end

  def show(conn, %{"id" => id}) do
    league = Organization.get_league!(id)
    Logger.debug("League value: #{inspect(league)}")
    render(conn, "show.json", league: league)
  end

  # Copied from the league_controller.. when we create the league, we want to respond through json and not use flash etc
  # create_league takes the current_user and inserts them into Repo.  We need to get the user from session or token in the json payload
  # get it from the token in the json payload
  def create(conn, params,3) do
    Logger.debug("inside bogus create #{inspect(params)}")
    conn
  end
  def create(conn, %{"league" => league_params}) do
    #require IEx when trouble shooting the params
    #IEx.pry()
    current_user = conn.assigns[:current_user]
    case Organization.create_league(current_user, league_params) do
      {:ok, league} ->
        conn
        |> render("ok.json", league: league)
      {:error, %Ecto.Changeset{} = changeset} ->
        Logger.debug(":error in changeset: #{inspect(changeset)}")
        render(conn, "new.json", changeset: changeset)
    end
  end
end

elixir/rs_umbrella/apps/rs_web/lib/rs_web/controllers/league_controller.ex
defmodule RsWeb.LeagueController do
  use RsWeb, :controller
  require Logger

  alias Rs.Organization
  alias Rs.Organization.League
  alias Rs.{Mailer, Email}

  plug :load_categories when action in [:new, :create, :edit, :update]

  def index(conn, _params, current_user) do
    leagues = Organization.list_user_leagues(current_user)
    render(conn, "index.html", leagues: leagues)
  end

  def action(conn, _) do
    args = [conn, conn.params, conn.assigns.current_user]
    apply(__MODULE__, action_name(conn), args)
  end

  def new(conn, _params, current_user) do
    changeset = Organization.change_league(current_user, %League{})
    Logger.info("changeset in new league #{inspect changeset} ")
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"league" => league_params}, current_user) do
    Logger.info('league_params coming in...')
    Logger.debug('league #{inspect(league_params)}')
    case Organization.create_league(current_user, league_params) do
      {:ok, league} ->
        conn
        |> put_flash(:info, "League created successfully.")
        |> redirect(to: Routes.league_path(conn, :show, league))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}, current_user) do
    league = Organization.get_user_league!(current_user, id)
    render(conn, "show.html", league: league)
  end

  def edit(conn, %{"id" => id}, current_user) do
    league = Organization.get_user_league!(current_user, id)
    changeset = Organization.change_league(current_user, league)
    render(conn, "edit.html", league: league, changeset: changeset)
  end

  def update(conn, %{"id" => id, "league" => league_params}, current_user) do
    league = Organization.get_user_league!(current_user, id)

    case Organization.update_league(league, league_params) do
      {:ok, league} ->
        conn
        |> put_flash(:info, "League updated successfully.")
        |> redirect(to: Routes.league_path(conn, :show, league))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", league: league, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}, current_user) do
    league = Organization.get_user_league!(current_user, id)
    {:ok, _league} = Organization.delete_league(league)

    conn
    |> put_flash(:info, "League deleted successfully.")
    |> redirect(to: Routes.league_path(conn, :index))
  end

  defp load_categories(conn, _) do
    assign(conn, :categories, Organization.list_alphabetical_categories())
  end
end

elixir/rs_umbrella/apps/rs_web/lib/rs_web/views/league_view.ex
defmodule RsWeb.LeagueView do
  use RsWeb, :view

  def category_select_options(categories) do
    for category <- categories, do: {category.name, category.id}
  end
end

elixir/rs_umbrella/apps/rs_web/lib/rs_web/templates/league/edit.html.eex
<div class="container">
<h1 class="h3 ml-3">Edit League</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.league_path(@conn, :update, @league)) %>

<span class="ml-3"><%= link "Back", to: Routes.league_path(@conn, :index) %></span>
</div>

elixir/rs_umbrella/apps/rs_web/lib/rs_web/templates/league/form.html.eex
<%= form_for @changeset, @action,[class: "form border rounded p-3 mb-3 ml-3 col-md-6" ], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
  <div class="form-group">
  <%= label f, :url %>
  <%= text_input f, :url , class: "form-control"%>
  <%= error_tag f, :url %>
</div>
  <div class="form-group">
  <%= label f, :name %>
  <%= text_input f, :name, class: "form-control" %> 
</div>
  <div class="form-group">
  <%= label f, :description %>
  <%= textarea f, :description, class: "form-control"  %>
  <%= error_tag f, :description %>
</div>
  <div class="form-group">
  <%= label f, :category_id, "Category"%>
  <%= select f, :category_id,
    category_select_options(@categories),
    prompt: "Choose a category" , class: "form-control"%>
  </div>
  <div>
    <%= submit "Save" %>
  </div>
<% end %>

elixir/rs_umbrella/apps/rs_web/lib/rs_web/templates/league/index.html.eex
<table class="table">
  <thead class="thead-light">
    <tr>
      <th>League Name</th>
        <th></th>
        <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for league <- @leagues do %>
    <tr>
      <td><%= league.name %></td>

      <td>
        <%= link "Visit", to: Routes.visit_path(@conn, :show, league) %>
        <%= link "Edit", to: Routes.league_path(@conn, :edit, league) %>
        <%= link "Delete", to: Routes.league_path(@conn, :delete, league), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New League", to: Routes.league_reg_path(@conn, :new) %></span>

elixir/rs_umbrella/apps/rs_web/lib/rs_web/templates/league/new.html.eex
<div id="elm-league1"></div>
<div id="elm-league-registration-main1"></div>
<div class="container">
<h1 class="h3 ml-3">New League</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.league_path(@conn, :create)) %>

<span class="ml-3"><%= link "Back", to: Routes.league_path(@conn, :index) %></span>
</div>

elixir/rs_umbrella/apps/rs_web/lib/rs_web/templates/league/show.html.eex
<h1>Show League</h1>

<ul>

  <li>
    <strong>Url:</strong>
    <%= @league.url %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @league.name %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @league.description %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.league_path(@conn, :edit, @league) %></span>
<span><%= link "Back", to: Routes.league_path(@conn, :index) %></span>